# -*- coding: utf-8 -*-
"""percobaan4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10x90SOju6HRCACCHakyNDuZQ4F-nJkUi
"""

from google.colab import drive
drive.mount('/content/gdrive')

#mengimpor library
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

#mengimpor dataset
dataset = pd.read_csv('/content/gdrive/My Drive/Pengunjung_mall.csv')
X = dataset.iloc[:, [3,4]].values

# menggunakan metode elbow untuk menentukan angka cluster yang tepat
from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('Metode Elbow')
plt.xlabel('Jumlah clusters')
plt.ylabel('WCSS')
plt.show()

#menjalankan k-means clustering ke dataset
kmeans = KMeans (n_clusters = 5,  init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

# Visualisai Hasil Clusters
plt.scatter(X[y_kmeans == 0,0], X[y_kmeans == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(X[y_kmeans == 1,0], X[y_kmeans == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(X[y_kmeans == 2,0], X[y_kmeans == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(X[y_kmeans == 3,0], X[y_kmeans == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(X[y_kmeans == 4,0], X[y_kmeans == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], s=300, c = 'yellow', label = 'Centroids')
plt.title('Clusters pelanggan')
plt.xlabel('Pendapatan Tahunan (Juta Rupiah)')
plt.ylabel('Rating Pengeluaran(1-100)')
plt.legend()
plt.show()